fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "karcersp2018@gmail.com"
        sender_name: "Garaz"
    registration:
            confirmation:
                enabled: true
#                from_email:
#                    address:        registration@garaz.com
#                    sender_name:    Demo Registration

#    resetting:
#            email:
#                from_email:
#                    address:        registration@garaz.com
#                    sender_name:    Demo Resetting